// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/config.dart';
import 'api/peer.dart';
import 'api/remote_client.dart';
import 'api/remote_host.dart';
import 'api/transfer.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiConfigInitRustLib();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1180893927;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutterdemo2',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiTransferCancelTransfer({required String transferId});

  void crateApiPeerClearAllPeers();

  void crateApiPeerConnectPeer({required String peerId});

  void crateApiTransferDebugPushMockReceiveEvent({
    required String fileName,
    required String message,
    required String senderPeerId,
  });

  String crateApiConfigDeviceId();

  Future<int> crateApiTransferFileServiceStart({int? preferredPort});

  Future<void> crateApiTransferFileServiceStop();

  String? crateApiConfigGetDefaultReceivePath();

  LocalProfileDto? crateApiConfigGetLocalProfile();

  Future<void> crateApiConfigInitRustLib();

  List<PeerInfoDto> crateApiPeerListKnownPeers();

  Future<LocalProfileDto> crateApiTypesLocalProfileDtoDefault();

  List<FileReceiveEventDto> crateApiTransferPullFileReceiveEvents();

  List<TransferProgressDto> crateApiTransferPullTransferProgress();

  String crateApiConfigRefreshSessionId();

  void crateApiPeerRegisterDiscoveredPeer({required PeerInfoDto peer});

  Future<void> crateApiRemoteClientRemoteClientConnect({
    required String host,
    required int port,
    required String sessionToken,
  });

  Future<void> crateApiRemoteClientRemoteClientDisconnect();

  void crateApiRemoteClientRemoteClientSendKey({
    required RemoteKeyEventDto event,
  });

  void crateApiRemoteClientRemoteClientSendPointer({
    required RemotePointerEventDto event,
  });

  VideoFrameDto? crateApiRemoteClientRemoteClientTryTakeRgbaFrame();

  void crateApiRemoteHostRemoteHostDispatchInput({
    required String sessionToken,
    required String payloadJson,
  });

  Future<int> crateApiRemoteHostRemoteHostStart({
    required String sessionToken,
    int? preferredPort,
  });

  Future<void> crateApiRemoteHostRemoteHostStop();

  Future<String> crateApiTransferSendFiles({required SendFilesRequestDto req});

  String crateApiConfigSessionId();

  void crateApiConfigSetDefaultReceivePath({required String path});

  void crateApiConfigSetLocalProfile({required LocalProfileDto profile});

  void crateApiConfigSetRustCacheDir({required String path});

  void crateApiConfigShutdownRustLib();

  void crateApiPeerUnregisterPeer({required String peerId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiTransferCancelTransfer({required String transferId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(transferId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiTransferCancelTransferConstMeta,
        argValues: [transferId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferCancelTransferConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_transfer",
        argNames: ["transferId"],
      );

  @override
  void crateApiPeerClearAllPeers() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiPeerClearAllPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPeerClearAllPeersConstMeta =>
      const TaskConstMeta(debugName: "clear_all_peers", argNames: []);

  @override
  void crateApiPeerConnectPeer({required String peerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiPeerConnectPeerConstMeta,
        argValues: [peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPeerConnectPeerConstMeta =>
      const TaskConstMeta(debugName: "connect_peer", argNames: ["peerId"]);

  @override
  void crateApiTransferDebugPushMockReceiveEvent({
    required String fileName,
    required String message,
    required String senderPeerId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fileName, serializer);
          sse_encode_String(message, serializer);
          sse_encode_String(senderPeerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiTransferDebugPushMockReceiveEventConstMeta,
        argValues: [fileName, message, senderPeerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferDebugPushMockReceiveEventConstMeta =>
      const TaskConstMeta(
        debugName: "debug_push_mock_receive_event",
        argNames: ["fileName", "message", "senderPeerId"],
      );

  @override
  String crateApiConfigDeviceId() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiConfigDeviceIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigDeviceIdConstMeta =>
      const TaskConstMeta(debugName: "device_id", argNames: []);

  @override
  Future<int> crateApiTransferFileServiceStart({int? preferredPort}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_16(preferredPort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiTransferFileServiceStartConstMeta,
        argValues: [preferredPort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferFileServiceStartConstMeta =>
      const TaskConstMeta(
        debugName: "file_service_start",
        argNames: ["preferredPort"],
      );

  @override
  Future<void> crateApiTransferFileServiceStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiTransferFileServiceStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferFileServiceStopConstMeta =>
      const TaskConstMeta(debugName: "file_service_stop", argNames: []);

  @override
  String? crateApiConfigGetDefaultReceivePath() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigGetDefaultReceivePathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigGetDefaultReceivePathConstMeta =>
      const TaskConstMeta(debugName: "get_default_receive_path", argNames: []);

  @override
  LocalProfileDto? crateApiConfigGetLocalProfile() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_local_profile_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigGetLocalProfileConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigGetLocalProfileConstMeta =>
      const TaskConstMeta(debugName: "get_local_profile", argNames: []);

  @override
  Future<void> crateApiConfigInitRustLib() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigInitRustLibConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigInitRustLibConstMeta =>
      const TaskConstMeta(debugName: "init_rust_lib", argNames: []);

  @override
  List<PeerInfoDto> crateApiPeerListKnownPeers() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_peer_info_dto,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiPeerListKnownPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPeerListKnownPeersConstMeta =>
      const TaskConstMeta(debugName: "list_known_peers", argNames: []);

  @override
  Future<LocalProfileDto> crateApiTypesLocalProfileDtoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_local_profile_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesLocalProfileDtoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesLocalProfileDtoDefaultConstMeta =>
      const TaskConstMeta(debugName: "local_profile_dto_default", argNames: []);

  @override
  List<FileReceiveEventDto> crateApiTransferPullFileReceiveEvents() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_file_receive_event_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferPullFileReceiveEventsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferPullFileReceiveEventsConstMeta =>
      const TaskConstMeta(debugName: "pull_file_receive_events", argNames: []);

  @override
  List<TransferProgressDto> crateApiTransferPullTransferProgress() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_transfer_progress_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferPullTransferProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferPullTransferProgressConstMeta =>
      const TaskConstMeta(debugName: "pull_transfer_progress", argNames: []);

  @override
  String crateApiConfigRefreshSessionId() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiConfigRefreshSessionIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigRefreshSessionIdConstMeta =>
      const TaskConstMeta(debugName: "refresh_session_id", argNames: []);

  @override
  void crateApiPeerRegisterDiscoveredPeer({required PeerInfoDto peer}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_peer_info_dto(peer, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiPeerRegisterDiscoveredPeerConstMeta,
        argValues: [peer],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPeerRegisterDiscoveredPeerConstMeta =>
      const TaskConstMeta(
        debugName: "register_discovered_peer",
        argNames: ["peer"],
      );

  @override
  Future<void> crateApiRemoteClientRemoteClientConnect({
    required String host,
    required int port,
    required String sessionToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(sessionToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiRemoteClientRemoteClientConnectConstMeta,
        argValues: [host, port, sessionToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoteClientRemoteClientConnectConstMeta =>
      const TaskConstMeta(
        debugName: "remote_client_connect",
        argNames: ["host", "port", "sessionToken"],
      );

  @override
  Future<void> crateApiRemoteClientRemoteClientDisconnect() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiRemoteClientRemoteClientDisconnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoteClientRemoteClientDisconnectConstMeta =>
      const TaskConstMeta(debugName: "remote_client_disconnect", argNames: []);

  @override
  void crateApiRemoteClientRemoteClientSendKey({
    required RemoteKeyEventDto event,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_remote_key_event_dto(event, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiRemoteClientRemoteClientSendKeyConstMeta,
        argValues: [event],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoteClientRemoteClientSendKeyConstMeta =>
      const TaskConstMeta(
        debugName: "remote_client_send_key",
        argNames: ["event"],
      );

  @override
  void crateApiRemoteClientRemoteClientSendPointer({
    required RemotePointerEventDto event,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_remote_pointer_event_dto(event, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiRemoteClientRemoteClientSendPointerConstMeta,
        argValues: [event],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoteClientRemoteClientSendPointerConstMeta =>
      const TaskConstMeta(
        debugName: "remote_client_send_pointer",
        argNames: ["event"],
      );

  @override
  VideoFrameDto? crateApiRemoteClientRemoteClientTryTakeRgbaFrame() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_video_frame_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRemoteClientRemoteClientTryTakeRgbaFrameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiRemoteClientRemoteClientTryTakeRgbaFrameConstMeta =>
      const TaskConstMeta(
        debugName: "remote_client_try_take_rgba_frame",
        argNames: [],
      );

  @override
  void crateApiRemoteHostRemoteHostDispatchInput({
    required String sessionToken,
    required String payloadJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionToken, serializer);
          sse_encode_String(payloadJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiRemoteHostRemoteHostDispatchInputConstMeta,
        argValues: [sessionToken, payloadJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoteHostRemoteHostDispatchInputConstMeta =>
      const TaskConstMeta(
        debugName: "remote_host_dispatch_input",
        argNames: ["sessionToken", "payloadJson"],
      );

  @override
  Future<int> crateApiRemoteHostRemoteHostStart({
    required String sessionToken,
    int? preferredPort,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionToken, serializer);
          sse_encode_opt_box_autoadd_u_16(preferredPort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiRemoteHostRemoteHostStartConstMeta,
        argValues: [sessionToken, preferredPort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoteHostRemoteHostStartConstMeta =>
      const TaskConstMeta(
        debugName: "remote_host_start",
        argNames: ["sessionToken", "preferredPort"],
      );

  @override
  Future<void> crateApiRemoteHostRemoteHostStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiRemoteHostRemoteHostStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoteHostRemoteHostStopConstMeta =>
      const TaskConstMeta(debugName: "remote_host_stop", argNames: []);

  @override
  Future<String> crateApiTransferSendFiles({required SendFilesRequestDto req}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_send_files_request_dto(req, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiTransferSendFilesConstMeta,
        argValues: [req],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferSendFilesConstMeta =>
      const TaskConstMeta(debugName: "send_files", argNames: ["req"]);

  @override
  String crateApiConfigSessionId() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiConfigSessionIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigSessionIdConstMeta =>
      const TaskConstMeta(debugName: "session_id", argNames: []);

  @override
  void crateApiConfigSetDefaultReceivePath({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiConfigSetDefaultReceivePathConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigSetDefaultReceivePathConstMeta =>
      const TaskConstMeta(
        debugName: "set_default_receive_path",
        argNames: ["path"],
      );

  @override
  void crateApiConfigSetLocalProfile({required LocalProfileDto profile}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_local_profile_dto(profile, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiConfigSetLocalProfileConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigSetLocalProfileConstMeta =>
      const TaskConstMeta(
        debugName: "set_local_profile",
        argNames: ["profile"],
      );

  @override
  void crateApiConfigSetRustCacheDir({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiConfigSetRustCacheDirConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigSetRustCacheDirConstMeta =>
      const TaskConstMeta(debugName: "set_rust_cache_dir", argNames: ["path"]);

  @override
  void crateApiConfigShutdownRustLib() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiConfigShutdownRustLibConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigShutdownRustLibConstMeta =>
      const TaskConstMeta(debugName: "shutdown_rust_lib", argNames: []);

  @override
  void crateApiPeerUnregisterPeer({required String peerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiPeerUnregisterPeerConstMeta,
        argValues: [peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPeerUnregisterPeerConstMeta =>
      const TaskConstMeta(debugName: "unregister_peer", argNames: ["peerId"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApiError dco_decode_api_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApiError(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  LocalProfileDto dco_decode_box_autoadd_local_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_local_profile_dto(raw);
  }

  @protected
  PeerInfoDto dco_decode_box_autoadd_peer_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_peer_info_dto(raw);
  }

  @protected
  RemoteKeyEventDto dco_decode_box_autoadd_remote_key_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_remote_key_event_dto(raw);
  }

  @protected
  RemotePointerEventDto dco_decode_box_autoadd_remote_pointer_event_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_remote_pointer_event_dto(raw);
  }

  @protected
  SendFilesRequestDto dco_decode_box_autoadd_send_files_request_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_send_files_request_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  VideoFrameDto dco_decode_box_autoadd_video_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_video_frame_dto(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FileReceiveEventDto dco_decode_file_receive_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FileReceiveEventDto(
      fileName: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
      senderPeerId: dco_decode_String(arr[2]),
      savedPath: dco_decode_opt_String(arr[3]),
      error: dco_decode_opt_String(arr[4]),
      timestampMs: dco_decode_i_64(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FileReceiveEventDto> dco_decode_list_file_receive_event_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_file_receive_event_dto)
        .toList();
  }

  @protected
  List<PeerInfoDto> dco_decode_list_peer_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_info_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TransferProgressDto> dco_decode_list_transfer_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_transfer_progress_dto)
        .toList();
  }

  @protected
  LocalProfileDto dco_decode_local_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LocalProfileDto(
      nickname: dco_decode_String(arr[0]),
      tags: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  LocalProfileDto? dco_decode_opt_box_autoadd_local_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_local_profile_dto(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  VideoFrameDto? dco_decode_opt_box_autoadd_video_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_video_frame_dto(raw);
  }

  @protected
  PeerInfoDto dco_decode_peer_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PeerInfoDto(
      peerId: dco_decode_String(arr[0]),
      instanceId: dco_decode_String(arr[1]),
      nickname: dco_decode_String(arr[2]),
      tags: dco_decode_list_String(arr[3]),
      host: dco_decode_String(arr[4]),
      fileServicePort: dco_decode_u_16(arr[5]),
      remoteDesktopPort: dco_decode_u_16(arr[6]),
    );
  }

  @protected
  RemoteKeyEventDto dco_decode_remote_key_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RemoteKeyEventDto(
      keyCode: dco_decode_i_32(arr[0]),
      down: dco_decode_bool(arr[1]),
      modifiers: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  RemotePointerEventDto dco_decode_remote_pointer_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RemotePointerEventDto(
      kind: dco_decode_String(arr[0]),
      x: dco_decode_f_64(arr[1]),
      y: dco_decode_f_64(arr[2]),
      button: dco_decode_i_32(arr[3]),
      delta: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  SendFilesRequestDto dco_decode_send_files_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SendFilesRequestDto(
      targetPeerId: dco_decode_String(arr[0]),
      filePaths: dco_decode_list_String(arr[1]),
      message: dco_decode_String(arr[2]),
    );
  }

  @protected
  TransferProgressDto dco_decode_transfer_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TransferProgressDto(
      transferId: dco_decode_String(arr[0]),
      bytesSent: dco_decode_i_64(arr[1]),
      totalBytes: dco_decode_i_64(arr[2]),
      phase: dco_decode_String(arr[3]),
      error: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoFrameDto dco_decode_video_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VideoFrameDto(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      rgba: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApiError sse_decode_api_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ApiError(code: var_code, message: var_message);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  LocalProfileDto sse_decode_box_autoadd_local_profile_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_local_profile_dto(deserializer));
  }

  @protected
  PeerInfoDto sse_decode_box_autoadd_peer_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_peer_info_dto(deserializer));
  }

  @protected
  RemoteKeyEventDto sse_decode_box_autoadd_remote_key_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_remote_key_event_dto(deserializer));
  }

  @protected
  RemotePointerEventDto sse_decode_box_autoadd_remote_pointer_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_remote_pointer_event_dto(deserializer));
  }

  @protected
  SendFilesRequestDto sse_decode_box_autoadd_send_files_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_send_files_request_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  VideoFrameDto sse_decode_box_autoadd_video_frame_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_video_frame_dto(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FileReceiveEventDto sse_decode_file_receive_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileName = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_senderPeerId = sse_decode_String(deserializer);
    var var_savedPath = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_timestampMs = sse_decode_i_64(deserializer);
    return FileReceiveEventDto(
      fileName: var_fileName,
      message: var_message,
      senderPeerId: var_senderPeerId,
      savedPath: var_savedPath,
      error: var_error,
      timestampMs: var_timestampMs,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FileReceiveEventDto> sse_decode_list_file_receive_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FileReceiveEventDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_file_receive_event_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PeerInfoDto> sse_decode_list_peer_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerInfoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_info_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TransferProgressDto> sse_decode_list_transfer_progress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TransferProgressDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transfer_progress_dto(deserializer));
    }
    return ans_;
  }

  @protected
  LocalProfileDto sse_decode_local_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nickname = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return LocalProfileDto(nickname: var_nickname, tags: var_tags);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  LocalProfileDto? sse_decode_opt_box_autoadd_local_profile_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_local_profile_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  VideoFrameDto? sse_decode_opt_box_autoadd_video_frame_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_video_frame_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PeerInfoDto sse_decode_peer_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_instanceId = sse_decode_String(deserializer);
    var var_nickname = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_fileServicePort = sse_decode_u_16(deserializer);
    var var_remoteDesktopPort = sse_decode_u_16(deserializer);
    return PeerInfoDto(
      peerId: var_peerId,
      instanceId: var_instanceId,
      nickname: var_nickname,
      tags: var_tags,
      host: var_host,
      fileServicePort: var_fileServicePort,
      remoteDesktopPort: var_remoteDesktopPort,
    );
  }

  @protected
  RemoteKeyEventDto sse_decode_remote_key_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keyCode = sse_decode_i_32(deserializer);
    var var_down = sse_decode_bool(deserializer);
    var var_modifiers = sse_decode_i_32(deserializer);
    return RemoteKeyEventDto(
      keyCode: var_keyCode,
      down: var_down,
      modifiers: var_modifiers,
    );
  }

  @protected
  RemotePointerEventDto sse_decode_remote_pointer_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    var var_button = sse_decode_i_32(deserializer);
    var var_delta = sse_decode_f_64(deserializer);
    return RemotePointerEventDto(
      kind: var_kind,
      x: var_x,
      y: var_y,
      button: var_button,
      delta: var_delta,
    );
  }

  @protected
  SendFilesRequestDto sse_decode_send_files_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_targetPeerId = sse_decode_String(deserializer);
    var var_filePaths = sse_decode_list_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return SendFilesRequestDto(
      targetPeerId: var_targetPeerId,
      filePaths: var_filePaths,
      message: var_message,
    );
  }

  @protected
  TransferProgressDto sse_decode_transfer_progress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transferId = sse_decode_String(deserializer);
    var var_bytesSent = sse_decode_i_64(deserializer);
    var var_totalBytes = sse_decode_i_64(deserializer);
    var var_phase = sse_decode_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return TransferProgressDto(
      transferId: var_transferId,
      bytesSent: var_bytesSent,
      totalBytes: var_totalBytes,
      phase: var_phase,
      error: var_error,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoFrameDto sse_decode_video_frame_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return VideoFrameDto(width: var_width, height: var_height, rgba: var_rgba);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_api_error(ApiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_local_profile_dto(
    LocalProfileDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_local_profile_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_peer_info_dto(
    PeerInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_peer_info_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_remote_key_event_dto(
    RemoteKeyEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_remote_key_event_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_remote_pointer_event_dto(
    RemotePointerEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_remote_pointer_event_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_send_files_request_dto(
    SendFilesRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_send_files_request_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_video_frame_dto(
    VideoFrameDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_video_frame_dto(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_file_receive_event_dto(
    FileReceiveEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.senderPeerId, serializer);
    sse_encode_opt_String(self.savedPath, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_i_64(self.timestampMs, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_file_receive_event_dto(
    List<FileReceiveEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_file_receive_event_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer_info_dto(
    List<PeerInfoDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_info_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_transfer_progress_dto(
    List<TransferProgressDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transfer_progress_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_local_profile_dto(
    LocalProfileDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nickname, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_local_profile_dto(
    LocalProfileDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_local_profile_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_video_frame_dto(
    VideoFrameDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_video_frame_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_peer_info_dto(PeerInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_String(self.instanceId, serializer);
    sse_encode_String(self.nickname, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.fileServicePort, serializer);
    sse_encode_u_16(self.remoteDesktopPort, serializer);
  }

  @protected
  void sse_encode_remote_key_event_dto(
    RemoteKeyEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.keyCode, serializer);
    sse_encode_bool(self.down, serializer);
    sse_encode_i_32(self.modifiers, serializer);
  }

  @protected
  void sse_encode_remote_pointer_event_dto(
    RemotePointerEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
    sse_encode_i_32(self.button, serializer);
    sse_encode_f_64(self.delta, serializer);
  }

  @protected
  void sse_encode_send_files_request_dto(
    SendFilesRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.targetPeerId, serializer);
    sse_encode_list_String(self.filePaths, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_transfer_progress_dto(
    TransferProgressDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.transferId, serializer);
    sse_encode_i_64(self.bytesSent, serializer);
    sse_encode_i_64(self.totalBytes, serializer);
    sse_encode_String(self.phase, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_frame_dto(
    VideoFrameDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }
}
