// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/config.dart';
import 'api/peer.dart';
import 'api/remote_client.dart';
import 'api/remote_host.dart';
import 'api/transfer.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApiError dco_decode_api_error(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  LocalProfileDto dco_decode_box_autoadd_local_profile_dto(dynamic raw);

  @protected
  PeerInfoDto dco_decode_box_autoadd_peer_info_dto(dynamic raw);

  @protected
  RemoteKeyEventDto dco_decode_box_autoadd_remote_key_event_dto(dynamic raw);

  @protected
  RemotePointerEventDto dco_decode_box_autoadd_remote_pointer_event_dto(
    dynamic raw,
  );

  @protected
  SendFilesRequestDto dco_decode_box_autoadd_send_files_request_dto(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  VideoFrameDto dco_decode_box_autoadd_video_frame_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FileReceiveEventDto dco_decode_file_receive_event_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FileReceiveEventDto> dco_decode_list_file_receive_event_dto(dynamic raw);

  @protected
  List<PeerInfoDto> dco_decode_list_peer_info_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TransferProgressDto> dco_decode_list_transfer_progress_dto(dynamic raw);

  @protected
  LocalProfileDto dco_decode_local_profile_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  LocalProfileDto? dco_decode_opt_box_autoadd_local_profile_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  VideoFrameDto? dco_decode_opt_box_autoadd_video_frame_dto(dynamic raw);

  @protected
  PeerInfoDto dco_decode_peer_info_dto(dynamic raw);

  @protected
  RemoteKeyEventDto dco_decode_remote_key_event_dto(dynamic raw);

  @protected
  RemotePointerEventDto dco_decode_remote_pointer_event_dto(dynamic raw);

  @protected
  SendFilesRequestDto dco_decode_send_files_request_dto(dynamic raw);

  @protected
  TransferProgressDto dco_decode_transfer_progress_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoFrameDto dco_decode_video_frame_dto(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApiError sse_decode_api_error(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  LocalProfileDto sse_decode_box_autoadd_local_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  PeerInfoDto sse_decode_box_autoadd_peer_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  RemoteKeyEventDto sse_decode_box_autoadd_remote_key_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  RemotePointerEventDto sse_decode_box_autoadd_remote_pointer_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  SendFilesRequestDto sse_decode_box_autoadd_send_files_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  VideoFrameDto sse_decode_box_autoadd_video_frame_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FileReceiveEventDto sse_decode_file_receive_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FileReceiveEventDto> sse_decode_list_file_receive_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PeerInfoDto> sse_decode_list_peer_info_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TransferProgressDto> sse_decode_list_transfer_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  LocalProfileDto sse_decode_local_profile_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  LocalProfileDto? sse_decode_opt_box_autoadd_local_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  VideoFrameDto? sse_decode_opt_box_autoadd_video_frame_dto(
    SseDeserializer deserializer,
  );

  @protected
  PeerInfoDto sse_decode_peer_info_dto(SseDeserializer deserializer);

  @protected
  RemoteKeyEventDto sse_decode_remote_key_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  RemotePointerEventDto sse_decode_remote_pointer_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  SendFilesRequestDto sse_decode_send_files_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  TransferProgressDto sse_decode_transfer_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoFrameDto sse_decode_video_frame_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_api_error(ApiError self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_local_profile_dto(
    LocalProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_peer_info_dto(
    PeerInfoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_remote_key_event_dto(
    RemoteKeyEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_remote_pointer_event_dto(
    RemotePointerEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_send_files_request_dto(
    SendFilesRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_video_frame_dto(
    VideoFrameDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_file_receive_event_dto(
    FileReceiveEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_receive_event_dto(
    List<FileReceiveEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_info_dto(
    List<PeerInfoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transfer_progress_dto(
    List<TransferProgressDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_profile_dto(
    LocalProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_local_profile_dto(
    LocalProfileDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_video_frame_dto(
    VideoFrameDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_info_dto(PeerInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_remote_key_event_dto(
    RemoteKeyEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remote_pointer_event_dto(
    RemotePointerEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_files_request_dto(
    SendFilesRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_progress_dto(
    TransferProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_frame_dto(VideoFrameDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
