// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// 配置持久化设备 ID 的目录；不传则使用系统临时目录下的子目录。
void setRustCacheDir({required String path}) =>
    RustLib.instance.api.crateApiConfigSetRustCacheDir(path: path);

/// 释放监听线程等资源；再次使用需由 Flutter 重新 `RustLib.init()`（或后续扩展热启动 API）。
void shutdownRustLib() => RustLib.instance.api.crateApiConfigShutdownRustLib();

String deviceId() => RustLib.instance.api.crateApiConfigDeviceId();

String sessionId() => RustLib.instance.api.crateApiConfigSessionId();

/// 生成新的会话 ID（例如用户重新登录）。
String refreshSessionId() =>
    RustLib.instance.api.crateApiConfigRefreshSessionId();

void setDefaultReceivePath({required String path}) =>
    RustLib.instance.api.crateApiConfigSetDefaultReceivePath(path: path);

String? getDefaultReceivePath() =>
    RustLib.instance.api.crateApiConfigGetDefaultReceivePath();

void setLocalProfile({required LocalProfileDto profile}) =>
    RustLib.instance.api.crateApiConfigSetLocalProfile(profile: profile);

LocalProfileDto? getLocalProfile() =>
    RustLib.instance.api.crateApiConfigGetLocalProfile();
