// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

void registerDiscoveredPeer({required PeerInfoDto peer}) =>
    RustLib.instance.api.crateApiPeerRegisterDiscoveredPeer(peer: peer);

void unregisterPeer({required String peerId}) =>
    RustLib.instance.api.crateApiPeerUnregisterPeer(peerId: peerId);

List<PeerInfoDto> listKnownPeers() =>
    RustLib.instance.api.crateApiPeerListKnownPeers();

void clearAllPeers() => RustLib.instance.api.crateApiPeerClearAllPeers();

/// 将后续 `send_files` 默认对端设为该 peer（仍可在请求里显式指定）。
void connectPeer({required String peerId}) =>
    RustLib.instance.api.crateApiPeerConnectPeer(peerId: peerId);
