// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

Future<void> remoteClientConnect({
  required String host,
  required int port,
  required String sessionToken,
}) => RustLib.instance.api.crateApiRemoteClientRemoteClientConnect(
  host: host,
  port: port,
  sessionToken: sessionToken,
);

Future<void> remoteClientDisconnect() =>
    RustLib.instance.api.crateApiRemoteClientRemoteClientDisconnect();

VideoFrameDto? remoteClientTryTakeRgbaFrame() =>
    RustLib.instance.api.crateApiRemoteClientRemoteClientTryTakeRgbaFrame();

void remoteClientSendPointer({required RemotePointerEventDto event}) => RustLib
    .instance
    .api
    .crateApiRemoteClientRemoteClientSendPointer(event: event);

void remoteClientSendKey({required RemoteKeyEventDto event}) =>
    RustLib.instance.api.crateApiRemoteClientRemoteClientSendKey(event: event);
