// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

Future<int> remoteHostStart({
  required String sessionToken,
  int? preferredPort,
}) => RustLib.instance.api.crateApiRemoteHostRemoteHostStart(
  sessionToken: sessionToken,
  preferredPort: preferredPort,
);

Future<void> remoteHostStop() =>
    RustLib.instance.api.crateApiRemoteHostRemoteHostStop();

/// 模拟客户端发来的输入（JSON 或后续二进制协议）；当前仅校验 token 占位。
void remoteHostDispatchInput({
  required String sessionToken,
  required String payloadJson,
}) => RustLib.instance.api.crateApiRemoteHostRemoteHostDispatchInput(
  sessionToken: sessionToken,
  payloadJson: payloadJson,
);
