// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

Future<int> fileServiceStart({int? preferredPort}) => RustLib.instance.api
    .crateApiTransferFileServiceStart(preferredPort: preferredPort);

Future<void> fileServiceStop() =>
    RustLib.instance.api.crateApiTransferFileServiceStop();

Future<String> sendFiles({required SendFilesRequestDto req}) =>
    RustLib.instance.api.crateApiTransferSendFiles(req: req);

void cancelTransfer({required String transferId}) =>
    RustLib.instance.api.crateApiTransferCancelTransfer(transferId: transferId);

List<FileReceiveEventDto> pullFileReceiveEvents() =>
    RustLib.instance.api.crateApiTransferPullFileReceiveEvents();

List<TransferProgressDto> pullTransferProgress() =>
    RustLib.instance.api.crateApiTransferPullTransferProgress();

/// 测试用：模拟本机收到一条文件记录（单机无对端时供 UI 联调）。
void debugPushMockReceiveEvent({
  required String fileName,
  required String message,
  required String senderPeerId,
}) => RustLib.instance.api.crateApiTransferDebugPushMockReceiveEvent(
  fileName: fileName,
  message: message,
  senderPeerId: senderPeerId,
);
