// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `new`

/// 业务错误，便于 Flutter 按 `code` 做分支提示。
class ApiError implements FrbException {
  final String code;
  final String message;

  const ApiError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

/// 接收端事件（文件名 + 留言等），供 Flutter 轮询或后续改为 Stream。
class FileReceiveEventDto {
  final String fileName;
  final String message;
  final String senderPeerId;
  final String? savedPath;
  final String? error;
  final PlatformInt64 timestampMs;

  const FileReceiveEventDto({
    required this.fileName,
    required this.message,
    required this.senderPeerId,
    this.savedPath,
    this.error,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      fileName.hashCode ^
      message.hashCode ^
      senderPeerId.hashCode ^
      savedPath.hashCode ^
      error.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileReceiveEventDto &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          message == other.message &&
          senderPeerId == other.senderPeerId &&
          savedPath == other.savedPath &&
          error == other.error &&
          timestampMs == other.timestampMs;
}

/// 本地身份（昵称 + 有序标签路径，如 会场 / 片区）。
class LocalProfileDto {
  final String nickname;
  final List<String> tags;

  const LocalProfileDto({required this.nickname, required this.tags});

  static Future<LocalProfileDto> default_() =>
      RustLib.instance.api.crateApiTypesLocalProfileDtoDefault();

  @override
  int get hashCode => nickname.hashCode ^ tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalProfileDto &&
          runtimeType == other.runtimeType &&
          nickname == other.nickname &&
          tags == other.tags;
}

/// Bonsoir 发现后注入 Rust 的对端信息。
class PeerInfoDto {
  final String peerId;
  final String instanceId;
  final String nickname;
  final List<String> tags;
  final String host;
  final int fileServicePort;
  final int remoteDesktopPort;

  const PeerInfoDto({
    required this.peerId,
    required this.instanceId,
    required this.nickname,
    required this.tags,
    required this.host,
    required this.fileServicePort,
    required this.remoteDesktopPort,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      instanceId.hashCode ^
      nickname.hashCode ^
      tags.hashCode ^
      host.hashCode ^
      fileServicePort.hashCode ^
      remoteDesktopPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerInfoDto &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          instanceId == other.instanceId &&
          nickname == other.nickname &&
          tags == other.tags &&
          host == other.host &&
          fileServicePort == other.fileServicePort &&
          remoteDesktopPort == other.remoteDesktopPort;
}

class RemoteKeyEventDto {
  final int keyCode;
  final bool down;
  final int modifiers;

  const RemoteKeyEventDto({
    required this.keyCode,
    required this.down,
    required this.modifiers,
  });

  @override
  int get hashCode => keyCode.hashCode ^ down.hashCode ^ modifiers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteKeyEventDto &&
          runtimeType == other.runtimeType &&
          keyCode == other.keyCode &&
          down == other.down &&
          modifiers == other.modifiers;
}

/// 控制端指针事件（坐标建议为被控端分辨率下的逻辑坐标，具体约定在协议文档中细化）。
class RemotePointerEventDto {
  final String kind;
  final double x;
  final double y;
  final int button;
  final double delta;

  const RemotePointerEventDto({
    required this.kind,
    required this.x,
    required this.y,
    required this.button,
    required this.delta,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      x.hashCode ^
      y.hashCode ^
      button.hashCode ^
      delta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemotePointerEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          x == other.x &&
          y == other.y &&
          button == other.button &&
          delta == other.delta;
}

/// 发送文件请求。
class SendFilesRequestDto {
  final String targetPeerId;
  final List<String> filePaths;
  final String message;

  const SendFilesRequestDto({
    required this.targetPeerId,
    required this.filePaths,
    required this.message,
  });

  @override
  int get hashCode =>
      targetPeerId.hashCode ^ filePaths.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendFilesRequestDto &&
          runtimeType == other.runtimeType &&
          targetPeerId == other.targetPeerId &&
          filePaths == other.filePaths &&
          message == other.message;
}

/// 发送进度（占位；完整协议落地后由后台任务推送）。
class TransferProgressDto {
  final String transferId;
  final PlatformInt64 bytesSent;
  final PlatformInt64 totalBytes;
  final String phase;
  final String? error;

  const TransferProgressDto({
    required this.transferId,
    required this.bytesSent,
    required this.totalBytes,
    required this.phase,
    this.error,
  });

  @override
  int get hashCode =>
      transferId.hashCode ^
      bytesSent.hashCode ^
      totalBytes.hashCode ^
      phase.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferProgressDto &&
          runtimeType == other.runtimeType &&
          transferId == other.transferId &&
          bytesSent == other.bytesSent &&
          totalBytes == other.totalBytes &&
          phase == other.phase &&
          error == other.error;
}

/// 一帧 RGBA 裸数据，供 Flutter `texture_rgba_renderer` 使用（当前占位返回空）。
class VideoFrameDto {
  final int width;
  final int height;
  final Uint8List rgba;

  const VideoFrameDto({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoFrameDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}
